services:

# Conteneur de la bdd MYSQL
  db:
    image: mysql:9.2.0
    restart: always 
    container_name: mysql_db 
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

    networks:
      - wp-network

# Conteneur Wordpress avec serveur Apache intégré
# Build de l'image docker personnalisée dans le dockerfile intégrant la CLI  
  wordpress:
    build: .
    restart: always
    container_name: wordpress_app
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wp_data:/var/www/html/wp-content
    networks:
      - wp-network

# Conteneur phpmyadmin 
  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    container_name: phpmyadmin
    depends_on:
      - db
    ports :
      - "8081:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge

volumes:
  wp_data:
  db_data:
